
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        name: Black
        args: ["--line-length", "119", "--force-exclude", "migrations", "-S"]
        language_version: python3.8

  - repo: local
    hooks:
      - id: flake8
        name: Flake8
        description: This hook runs flake8
        entry: flake8 --config=./backend/.flake8
        language: python

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
