version: '3.6'

services:
  database:
    container_name: todo-list
    image: postgres:11
    volumes:
      - 'dbdata:/var/lib/postgresql/data'
    env_file:
      - .db.env
    ports:
      - 5434:5432

volumes:
  dbdata:
