name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    # - name: Copying configurations
    #   run: cp contrib/env-sample .env

    # - name: Install Poetry
    #   uses: Gr1N/setup-poetry@v4

    # - name: Set Poetry Config
    #   run: |
    #     poetry config virtualenvs.in-project false
    #     poetry config virtualenvs.path ~/.virtualenvs
    # - name: Install Dependencies
    #   run: poetry install

    # - name: Lynt with Flake8
    #   run: |
    #     poetry run flake8 --config=.flake8
    # - name: Tests with Pytest
    #   run: |
    #     poetry run pytest --cov=planilha
    # - name: Posting Coverage
    #   env:
    #     codecov_token: ${{ secrets.CODECOV_TOKEN }}
    #   run: |
    #     poetry run codecov
