name: Actions-CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Copiando Configurações
      run: cp contrib/env-sample .env

    - name: Instalando Poetry
      uses: Gr1N/setup-poetry@v4
      run: |
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs

    - name: Instalando as Dependências
      run: poetry install

    - name: Rodando os Testes
      run: poetry run pytest --cov=todo

    # - name: Posting Coverage
    #   env:
    #     codecov_token: ${{ secrets.CODECOV_TOKEN }}
    #   run: |
    #     poetry run codecov
